### ISSUE TITLE
Sprint 15: ревьюеру

### ISSUE THREAD

**Issue by SShliakhin** [SShliakhin/YP-Tracker#8]
Привет, Амир!
Пишу в ответ на твою проверку, в оригинал буду вставлять свои ответы

Проверил твою работу:

1. ❌ Есть грубые ошибки:

Есть ошибочные force-операций (в файле UIView+Constraints.swift можно сделать опциональный superview и там, где нужно это свойство через guard разворачивать опционал

**Мой ответ:**
`Посмотри на мое решение как на компромисс: если программист ошибся, то он получит assert сообщение с понятной причиной. А если при этом я буду использовать guard, как ты предлагаешь, то ошибку верстки, причина которой не ясна. Я выбрал assert.`

2. Завершены работы над экраном добавления новой привычки. На этот экран добавлены:

  ✅ - коллекция для выбора эмоджи (помните, что выбрать можно только одну эмоджи; выделяем её серым фоном);
  ✅ - коллекция для выбора цвета (цвет тоже можно выбрать только один; выделяем его тонким обрамлением);
  ✅ - кнопка для перехода к экрану с категориями (или ничего, если мы пока не будем никуда переходить);
  ✅ - кнопка для перехода на экран с расписанием (отображаем её, если пользователь ранее указывал, что хочет добавить «Привычку», а не «Нерегулярное событие»).

3. Реализован слой работы с базой данных с использованием надлежащих абстракций:

  ✅❌ - добавлены классы TrackerStore, TrackerCategoryStore, TrackerRecordStore для абстрагирования Core Data;

**Мой ответ:**
`Для абстракции у меня созданы сервисы CoreDataStack и CategoriesManagerCD, они справляются с задачей. Я не смог понять пользу от решения с TrackerStore, TrackerCategoryStore, TrackerRecordStore, расскажи пожалуйста`

  ✅ - добавлены Entity для хранения Tracker, TrackerCategory, TrackerRecord; у каждой Entity имеется префикс, четко обозначющий, что она используется для хранения в Core Data (например, TrackerCoreData);
  ✅ - в модели (файл с расширением .xcdatamodeld) указаны взаимосвязи между Entity;
  ❌ - для своевременного получения обновлений от Core Data используется NSFetchedResultsController;

**Мой ответ:**
`В описании работы я написал почему не использую NSFetchedResultsController. Я ожидаю какие то аргументы против, если вы заносите этот пункт в ошибку. В идеале жду предложений и помощи`

  ❌ - можно создавать привычки и нерегулярные события и после перезапуска информация отображается; иначе говоря - слой хранения данных (на базе Core Data) выполняет свои задачи;

**Мой ответ:**
`На лицо конфликт ТЗ и чек листа. В ТЗ нет необходимости предоставлять возможность создавать категории, а в чек листе проверяется создание привычек, которые без категорий создать не получается. У меня есть предзагрузка базы и поэтому это вылетело из головы. Я сделаю экран для создания категории.`

  ✅ -  нигде, кроме Store.swift файлов, нет строчки import CoreData; иначе говоря - приложение надежно абстрагировано от Core Data.

-----------------------------
⚠️ Критические замечания 

1. Линтер прерывает компиляцию из-за своих правил, приложение не компилируется (исправляется за 1 секунду, лишний пробел)

**Мой ответ:**
`В readme.md проекта указано как установить линтер, правила включены в проект (или нет?). У меня все собирается успешно. Уточни, пожалуйста`

2. NSFetchedResultsController используется только в каком-то CoreDataTrainerViewController, непонятно что это и зачем нужно

**Мой ответ:**
`В описании к работе указано зачем мне нужен CoreDataTrainerViewController и почему я его оставил`

3. Привычки и нерегулярные события создать невозможно, так как нельзя выбрать или добавить категорию (кнопка "добавить категорию" нажимается, но ничего не происходит)

**Мой ответ:**
`Ответил выше`

Без исправлений этих пунктов, я не смогу принять у тебя работу. Если возникнут вопросы, обязательно задавай их Наставнику!

----------------------
🍏 Рекомендации, не влияющие на результат проверки работы

1. Убирать лишние принты и вспомогательные файлы по типу CoreDataTrainerViewController

**Мой ответ:**
`В финале обязательно уберу, сейчас принты нужны как заглушки, либо как информация для контроля за циклами ссылок или где лежит БД`

2. Также много где поехал код-стайл, рекомендую его тоже поправить

**Мой ответ:**
`Важная рекомендация, только я не знаю где он поехал, уточни, пожалуйста.`

Комментарии ревью оставлены в пул-реквесте.
Жду исправлений :)

**Comment by amardanov** [comment]
Привет, по поводу комментов
1) Хорошо, оставим пока так, но скажу так, в проде `assert` используется только для тестирования. Нужно стараться писать такой код, который будет нормально себя вести без ассертов и форсов
2) по поводу ✅❌ где пункт абстракции это я забыл убрать крестик, все хорошо там
3) _"В описании работы я написал почему не использую NSFetchedResultsController."_ так и не увидел этой строчки нигде. Напиши сюда пожалуйста

4) _"В ТЗ нет необходимости предоставлять возможность создавать категории"_ ну если не было изначально категорий, то тогда можно было их создавать при первом запуске приложения и сохранять флаг, что категории загружены в `UserDefaults`, а потом проверять, что они есть и не создавать их заново

5) По поводу линтера. Он у меня есть и ругается на строчку `private var completions: [UIViewController : () -> Void]` из-за пробела после `UIViewController`

**Comment by SShliakhin** [comment]
не смог найти места для FRC в архитектуре Clean Swift, конечно были идеи немного нарушить концепцию, но последней каплей стало знание, что нам придется делать дальше - реализовывать пины для трекеров, здесь FRC вообще не знаю как может помочь?

**Comment by SShliakhin** [comment]
Ревьюер принял работу
